Update deploy-strapi.yml

diff --git a/.github/workflows/deploy-strapi.yml b/.github/workflows/deploy-strapi.yml
--- a/.github/workflows/deploy-strapi.yml
+++ b/.github/workflows/deploy-strapi.yml
@@ -158,7 +158,16 @@ jobs:
 
 
 
+      - name: DEBUG — Show server.ts content after override
+        run: |
+          echo "📄 Printing server.ts to verify override..."
+          ls -R ecommpoc/my-strapi-project/config || true
+          echo "------- FILE CONTENT BELOW -------"
+          cat ecommpoc/my-strapi-project/config/server.ts || echo "❌ server.ts NOT FOUND"
+          echo "----------------------------------"
 
+
+      
       - name: Create Dockerfile dynamically (inside my-strapi-project)
         working-directory: ecommpoc/my-strapi-project
         run: |
